### ISSUE TITLE
TFS 34800 New Starts not finding existing former subscription.

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/Advance---MI-Merge#71] opened 2017-03-10 21:50 UTC
I tried to do a new start on a former sub.  In this case grace owed.  I exactly matched what is in DTI occupant phone & address however the system created a new account.  

<img width="787" alt="screen shot 2017-03-10 at 4 23 29 pm" src="https://cloud.githubusercontent.com/assets/25616598/23814360/435e4dd0-05b1-11e7-82c9-4c8378b64e38.png">
<img width="1136" alt="screen shot 2017-03-10 at 4 21 58 pm" src="https://cloud.githubusercontent.com/assets/25616598/23814370/4a40b7aa-05b1-11e7-973b-5e3959764221.png">
<img width="822" alt="screen shot 2017-03-10 at 4 38 32 pm" src="https://cloud.githubusercontent.com/assets/25616598/23814408/6732ddfc-05b1-11e7-99a4-23e8e8424fce.png">
<img width="993" alt="screen shot 2017-03-10 at 4 50 01 pm" src="https://cloud.githubusercontent.com/assets/25616598/23814471/a935ae28-05b1-11e7-824e-43512b7fcab9.png">

**Comment by jvanzomeren** [comment] 2017-03-10 22:35
Becky and I are trying to confirm seems like maybe a problem with the API call.

**Comment by beckywallace** [comment] 2017-03-13 13:39
OK, I've recreated with a former subscriber I've verified I was able to retrieve via the API.  See attached document.  

[LTE start on former sub with balance.docx](https://github.com/mkoza178/Advance---MI-Merge/files/838311/LTE.start.on.former.sub.with.balance.docx)

**Comment by beckywallace** [comment] 2017-03-13 18:52
Subscriber is stopped with a balance owed.  Subscriber 150740, address ID 473795, occupant ID 1199768.  Balance owed:  50.96:

![image](https://cloud.githubusercontent.com/assets/25667903/23870326/0f423f08-07f4-11e7-8d97-8d26bb2221f8.png)

Able to find address/occupant via API:

![image](https://cloud.githubusercontent.com/assets/25667903/23870331/193bbd9a-07f4-11e7-859d-ca2b70b5b460.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23870336/1e0ac0e6-07f4-11e7-801d-2a5a76924d33.png)

New subscription started (354412):

![image](https://cloud.githubusercontent.com/assets/25667903/23870351/27baa2e6-07f4-11e7-96bc-2d1deda07ab7.png)

Event IDs:
![image](https://cloud.githubusercontent.com/assets/25667903/23870365/328243dc-07f4-11e7-9478-62f7405c9094.png)

**Comment by mkoza178** [comment] 2017-03-13 19:40
Reviewing this with my team.

**Comment by mkoza178** [comment] 2017-03-13 20:14
Confirmed. Something not right going on here. The sproc itself works right but from the application it returns me the wrong occupant id.

**Comment by mkoza178** [comment] 2017-03-15 14:39
TFS 34800

**Comment by apattok** [comment] 2017-03-24 15:16
ready to test

**Comment by beckywallace** [comment] 2017-03-28 15:35
According the flow for New Starts on a former sub with a balance, the following events should be fired:

![image](https://cloud.githubusercontent.com/assets/25667903/24413616/9a3aa93e-13a1-11e7-9dfa-4a81c5a974a7.png)

When doing a new start for an occupant / address combination that is stopped with a balance owed, these are the only events being fired (it appears the New Start is being fired BEFORE the address/occupant lookup and nothing happens after the Get Subscription Information):

![image](https://cloud.githubusercontent.com/assets/25667903/24413678/c5c5165c-13a1-11e7-8876-bec08dfb51f2.png)

This test was for Occupant / Address ID 1216037.  The subscriber is stopped (active = no, gets paper = no).  I'm unable to see the detail behind the New Start event to see why the error "Subscriber Already has an Active product" is returned.

**Comment by mkoza178** [comment] 2017-03-29 16:37
Okay I tested this and it's working now. I fired data for a previous subscription and it was found and sent.

**Comment by mkoza178** [comment] 2017-03-29 19:49
Hey guys, I think we are all set here. I ran a test, looks good. Becky ran a test and confirmed. Let me know!

**Comment by beckywallace** [comment] 2017-03-29 19:51
Just pending seeing the 947 fire...

**Comment by beckywallace** [comment] 2017-03-30 20:11
I ran a test and saw everything happen as expected, up to and through the 947 event.  This one can be CLOSED (but I can't close it because I'm not the author)

**Closed as completed** 2017-03-30 20:11 UTC
