### ISSUE TITLE
Restart Payment file shows $0.00 payment amount

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#80] opened 2017-03-17 14:00 UTC
Submitted a payment to restart subscriber 46230 (See event ID 590779).  Payment came in on SolicitorConPayments file (payment was submitted via Member site), and shows $0.00 payment amount (should have been $3.87)

![image](https://cloud.githubusercontent.com/assets/25667903/24046294/138c638c-0af0-11e7-872d-c0bb25fdb6cc.png)

**Comment by mkoza178** [comment] 2017-03-17 19:47
A dupe of github #76

**Closed as completed by mkoza178** 2017-03-17 19:47 UTC
